/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PickRouteImport } from './routes/pick'
import { Route as ReplenishRouteImport } from './routes/replenish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickRoute = PickRouteImport.update({
  id: '/pick',
  path: '/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplenishRoute = ReplenishRouteImport.update({
  id: '/replenish',
  path: '/replenish',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pick': typeof PickRoute
  '/replenish': typeof ReplenishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pick': typeof PickRoute
  '/replenish': typeof ReplenishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pick': typeof PickRoute
  '/replenish': typeof ReplenishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pick' | '/replenish'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pick' | '/replenish'
  id: '__root__' | '/' | '/pick' | '/replenish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PickRoute: typeof PickRoute
  ReplenishRoute: typeof ReplenishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick': {
      id: '/pick'
      path: '/pick'
      fullPath: '/pick'
      preLoaderRoute: typeof PickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replenish': {
      id: '/replenish'
      path: '/replenish'
      fullPath: '/replenish'
      preLoaderRoute: typeof ReplenishRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PickRoute: PickRoute,
  ReplenishRoute: ReplenishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
